# syntax=docker/dockerfile:1
#
# Strata — AMD RDNA build for gfx1201 (RX 9070 / 9070 XT), self-contained service image.
#
# The engine is compiled during `docker build` (GitHub Actions has no GPU, so the
# card is pinned via CMAKE_HIP_ARCHITECTURES). First container start then only
# downloads the model pack (~70 GB) and serves an OpenAI/Anthropic-compatible API.
#
# Why this shape (vs the ROCmFPX builder): Strata is not a drop-in binary — it is
# a C++ engine + Python server + model pack, so it runs as its own container
# (like the Bonsai sidecar), not by copying files into llama-swap's bin folder.
#
# Portability: GitHub runners have AVX-512; the target host (Ryzen 7 5700X) does
# not. Strata's setup.py normally leaves GGML_NATIVE=ON, which would bake in the
# runner's ISA and crash the host with 'Illegal instruction' — the same class of
# bug as the ROCmFPX build. -DSTRATA_PORTABLE=ON is Strata's own switch for this:
# AVX2 baseline (AVX/AVX2/FMA/F16C/BMI2), no AVX-512, and it matches what
# setup.py expects on an AVX2 host (empty isa_floor), so the runtime setup pass
# keeps the compiled engine instead of recompiling.
#
# ROCm: rocm/dev-ubuntu-24.04:7.14.1-full ships the HIP dev stack AND the runtime
# libraries in one image, so build and run never disagree about versions.
# (Strata's own HIP benchmarks use ROCm 7.x; system minimum is 7.0.)

ARG ROCM_TAG=7.14.1-full
FROM rocm/dev-ubuntu-24.04:${ROCM_TAG} AS build

ENV DEBIAN_FRONTEND=noninteractive \
    ROCM_PATH=/opt/rocm \
    HIP_PLATFORM=amd \
    HIP_COMPILER=clang \
    HIP_RUNTIME=rocclr

RUN apt-get update && apt-get install -y --no-install-recommends \
      python3.12 python3.12-venv python3-pip git ca-certificates unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/strata

# Pinned to the tag this Dockerfile was written against (verified locally);
# bump deliberately — setup.py recompiles only when its source hash changes.
ARG STRATA_REF=v0.1.39
RUN git clone --depth 1 --branch "${STRATA_REF}" https://github.com/Niko1221/Strata . \
    && git log -1 --format="Strata %h %s"

# Python runtime (server, tools). setup.py manages this venv at start too.
RUN python3.12 -m venv .venv \
    && .venv/bin/pip install --quiet --disable-pip-version-check -r requirements.txt

# llama.cpp at the commit Strata pins — exactly as setup.py.get_llama_cpp() does,
# so the engine's ggml matches what the source tree expects.
RUN .venv/bin/python - <<'PY'
import sys, urllib.request
sys.path.insert(0, ".")
from setup import LLAMA_CPP_ZIP, ROOT
dest = ROOT / "third_party" / "llama.cpp.zip"
print("downloading", LLAMA_CPP_ZIP)
urllib.request.urlretrieve(LLAMA_CPP_ZIP, dest)
print("saved", dest)
PY

# Compile the HIP engine for gfx1201. Flags mirror setup.py:build_engine_hip()
# (line ~1887 of v0.1.39), plus STRATA_PORTABLE=ON (see header). CMake's own
# hip_backend.cmake resolves the ROCm targets; STRATA_GGML_DIR points ggml at the
# pinned llama.cpp checkout instead of a second network fetch.
RUN .venv/bin/python - <<'PY'
import sys, zipfile, shutil
from pathlib import Path
sys.path.insert(0, ".")
from setup import ROOT
z = ROOT / "third_party" / "llama.cpp.zip"
tmp = ROOT / "third_party" / "_unpack"
with zipfile.ZipFile(z) as f:
    f.extractall(tmp, [m for m in f.namelist() if "/tools/ui/" not in m])
top = next(tmp.iterdir())
shutil.rmtree(ROOT / "third_party" / "llama.cpp", ignore_errors=True)
shutil.move(str(top), str(ROOT / "third_party" / "llama.cpp"))
shutil.rmtree(tmp, ignore_errors=True)
z.unlink()
print("llama.cpp unpacked at", ROOT / "third_party" / "llama.cpp")
PY

ARG HIP_ARCHS=gfx1201
RUN bitcode=/opt/rocm/lib/llvm/amdgcn/bitcode \
    && .venv/bin/cmake -S . -B build-hip \
      -DCMAKE_BUILD_TYPE=Release \
      -DSTRATA_ENABLE_HIP=ON \
      -DSTRATA_ENABLE_CUDA=OFF \
      -DSTRATA_BUILD_TESTS=OFF \
      -DSTRATA_PREFILL_MMQ=ON \
      -DSTRATA_PORTABLE=ON \
      -DCMAKE_HIP_ARCHITECTURES="${HIP_ARCHS}" \
      -DCMAKE_HIP_COMPILER=/opt/rocm/llvm/bin/clang++ \
      -DCMAKE_HIP_COMPILER_ROCM_ROOT=/opt/rocm \
      -DCMAKE_PREFIX_PATH="/opt/rocm;/opt/rocm/lib" \
      -DCMAKE_HIP_FLAGS="--rocm-path=/opt/rocm --rocm-device-lib-path=${bitcode}" \
      -DSTRATA_GGML_DIR=/opt/strata/third_party/llama.cpp \
    && .venv/bin/cmake --build build-hip --target strata -j "$(nproc)"

# Install the engine where setup.py looks (engine/), with a BUILD.json that
# matches what setup.py:build_engine_hip() would write — generated by Strata's
# own module so the source hash can't drift. A mismatched stamp makes setup.py
# try to recompile at container start; this must be exact.
RUN mkdir -p engine \
    && cp build-hip/strata engine/strata \
    && .venv/bin/python - <<'PY'
import json, sys
from pathlib import Path
sys.path.insert(0, ".")
import setup as S
eng = S.ROOT / "engine"
meta = {
    "source": "local-hip",
    "backend": "hip",
    "version": S.source_version(),
    "archs": ["gfx1201"],
    "vision": "none",
    "lib_dirs": ["/opt/rocm/lib"],
    "src": S.source_hash(S.ENGINE_SOURCES),
}
(eng / "BUILD.json").write_text(json.dumps(meta, indent=1))
print("engine installed:", eng / "strata", "stamp:", meta["version"])
PY

# Drop the build tree; keep the source (setup.py runs from it at start) and the
# venv. The engine binary + BUILD.json are what the container serves with.
RUN rm -rf build-hip \
    && find third_party/llama.cpp -name "*.zip" -delete

EXPOSE 8080
VOLUME ["/data", "/models"]

COPY docker-entrypoint.sh /opt/strata/docker-entrypoint.sh
RUN chmod +x /opt/strata/docker-entrypoint.sh

WORKDIR /opt/strata
ENTRYPOINT ["/opt/strata/docker-entrypoint.sh"]
